# Generated by Django 4.2.4 on 2024-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_rename_medical_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='latitude',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='longitude',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
