# Generated by Django 4.2.4 on 2024-01-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_certification_latitude_certification_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
