# Generated by Django 4.2.4 on 2024-01-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_seller_latitude_alter_seller_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_image',
            field=models.ImageField(blank=True, null=True, upload_to='certification_images/'),
        ),
    ]
