# Generated by Django 4.2.4 on 2024-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_alter_certification_certification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expiry_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
