# Generated by Django 4.2.4 on 2024-01-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_certification_expiry_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
