# Generated by Django 4.2.4 on 2024-01-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_certification_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='longitude',
        ),
    ]
