# Generated by Django 4.2.4 on 2024-01-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_alter_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
