# Generated by Django 4.2.4 on 2024-01-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_remove_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=20),
        ),
    ]
