# Generated by Django 4.2.4 on 2024-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='is_approved',
            field=models.CharField(choices=[('updated', 'updated'), ('notupdated', 'notupdated')], default='notupdated', max_length=10),
        ),
    ]
