# Generated by Django 4.2.4 on 2024-02-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_deliveryagent_availability_deliveryagent_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
    ]
