# Generated by Django 4.2.4 on 2024-02-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_deliveryagent_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='seller',
        ),
    ]
