# Generated by Django 4.2.4 on 2024-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_remove_deliveryagent_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0.0, max_digits=20, null=True),
        ),
    ]
