# Generated by Django 4.2.4 on 2024-02-20 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0081_assigndeliveryagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigndeliveryagent',
            name='order',
        ),
        migrations.AddField(
            model_name='assigndeliveryagent',
            name='orderitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.orderitem'),
        ),
        migrations.AddField(
            model_name='assigndeliveryagent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='UserAgentDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.deliveryagent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'agent')},
            },
        ),
    ]
