# Generated by Django 4.2.4 on 2024-02-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0082_remove_assigndeliveryagent_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndeliveryagent',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.orderitem'),
        ),
    ]
