# Generated by Django 4.2.4 on 2024-02-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_alter_assigndeliveryagent_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigndeliveryagent',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='assigndeliveryagent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order'),
        ),
    ]
