# Generated by Django 4.2.4 on 2024-02-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0084_remove_assigndeliveryagent_orderitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assigndeliveryagent',
        ),
    ]
