# Generated by Django 4.2.4 on 2024-02-20 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0085_delete_assigndeliveryagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigndeliveryagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('billingdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.billingdetails')),
                ('deliveryagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.deliveryagent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
