# Generated by Django 4.2.4 on 2024-02-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_remove_order_deliveryagent_orderitem_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='agent_is_approved',
            field=models.CharField(choices=[('delivered', 'delivered'), ('notdelivered', 'notdelivered')], default='notdelivered', max_length=20),
        ),
    ]
