# Generated by Django 4.2.4 on 2024-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_orderitem_agent_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('notavailable', 'notavailable')], default='notavailable', max_length=15),
        ),
    ]
