# Generated by Django 4.2.4 on 2024-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_alter_deliveryagent_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
    ]
