# Generated by Django 4.2.4 on 2024-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0091_alter_deliveryagent_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndeliveryagent',
            name='assigned_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
