# Generated by Django 4.2.4 on 2024-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0093_deliveryreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_choice',
            field=models.CharField(choices=[('order', 'order'), ('reserve', 'reserve'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
