# Generated by Django 4.2.4 on 2024-03-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0096_orderitem_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
