# Generated by Django 4.2.4 on 2024-03-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0097_orderitem_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_not_valid',
            field=models.BooleanField(default=False),
        ),
    ]
